### ISSUE TITLE
Idea: Queuing

### ISSUE THREAD

**Issue by pedromellofh** [mhogomchungu/tasks#3]
It would be nice to put a series of async calls to compose a indexed queue which, on complete, shoud execute a trigger. something like this:

```cpp
Task::queue([] {
    Task::run( fn1 ).then( use1 );
    Task::run( fn2 ).then( use2 );
    Task::run( fn3 ).then( use3 );
}).then( doSomething );
```

I believe this is better than a sequence of await() calls, because it would take advantage of using many threads as possible.

**Comment by mhogomchungu** [comment]
I think its possible to do what you ask but the API will have to be different and used as it is shown below:

```
Task::queue( {fn1,use1},{fn2,use2},{fn3,use3} ).then( doSomething );

```

Another useful API will be used as below:

```
Task::queue( fn1,fn2,fn3 ).then( doSomething );
```

Where those three functions will run on 3 different threads and then "doSomething" will be called when all 3 complete.

Will look into implementing them shortly.

**Comment by mhogomchungu** [comment]
I just made a commit[1]

There are two API and they can be used as follows:

```
Task::future< void >& e = Task::run(  fn1,fn2,fn3 ) ;
```

```
Task::future< void >& f1 = Task::run( fn1 ) ;
Task::future< void >& f2 = Task::run( fn2 ) ;
Task::future< void >& f3 = Task::run( fn3 ) ;

Task::future< void >& e = Task::run(  f1,f2,f3 ) ;
```

1. .await() can then be called on the future to wait for all tasks to finish before continuing.
2. .then() can then be called on the future to invoke a callback on the current thread when all tasks finish.

[1] https://github.com/mhogomchungu/tasks/commit/40a9835b3968ed121240768c5fe9e8e272c02a24

**Comment by mhogomchungu** [comment]
Just made another commit[1] that should close this bug

The functionality you seek can be achieved with something like below:
```
	auto fn1 = [](){ } ;
	auto fn2 = [](){ } ;
	auto fn3 = [](){ } ;

	auto r1 = [](){ } ;
	auto r2 = [](){ } ;
	auto r3 = [](){ } ;

	Task::future<void>& e = Task::run( Task::pair{ fn1,r1 },
					   Task::pair{ fn2,r2 },
					   Task::pair{ fn3,r3 } ) ;
```
Each Task is paired with its own continuation and a future is returned and can be normally.

[1] https://github.com/mhogomchungu/tasks/commit/333d9840ac2e51bd82ff2f78de445a8cbd18051d

**Comment by mhogomchungu** [comment]
Just though i should update this thread to say an example of a complete API use with continuations that take argument and continuations that do not take arguments is here[1]

[1] https://github.com/mhogomchungu/tasks/blob/eca7e2abe10d62f1cad0b5d22c0a77f7b9d9f143/example.cpp#L182

**Comment by mhogomchungu** [comment]
I think you originally wanted all your tasks to run sequentially and then to run a trigger after the last one finish and i just added an API to do just that

The API can be used as shown below:

```
Task::future<void>& e = Task::run( Task::pair{ fn1,use1 },
					              Task::pair{ fn2,use2 },
					              Task::pair{ fn3,use3 } )  ;

e.queue( doSomething ) ;
```
If you want to use as many threads as possible then you have to run your tasks concurrently and their an API for this.

If you want to run your tasks sequentially(with the API i just added) then a single thread potentially the same one( Qt reuses threads) will be used for all tasks.
