### ISSUE TITLE
Feature request: Task progress

### ISSUE THREAD

**Issue by JacksiroKe** [mhogomchungu/tasks#6]
Hey @mhogomchungu Asante sana for writing this particular library since task management is something that has been missing for Qt and all the other attempts made online were not doing it like the way we have always desired. Your solution seems to address the Async Wait via Task::await().

Now I may want to show my users progress in terms of a progress bar or percentage. Would you mind considering adding that for me please.

**Comment by mhogomchungu** [comment]
Done and the example use is here below:

```
void example::run()
{
	auto run_main = []( int x ){

		//This lambda will be executable on the thread 
		"example::run()" is on and its usually GUI thread.

		"x" is the current progress.
	} ;

	auto run_bg = []( const Task::progress& pp ){

		//This lambda will be executable on the
		background thread.

		for(int i = 0 ; i < 5 ;i++ ){

			// update progress
			pp.update( i ) ;

			//simulate long delay
			QThread::currentThread()->sleep(1); 
		}
	} ;

	Task::run( this,run_bg,run_main ).await() ;
}
```

**Comment by JacksiroKe** [comment]
Thanks for the quick response sir, I will check, code, debug and get back to you asap

**Comment by mhogomchungu** [comment]
Closing this one as fixed, feel free to comment if anything comes up.
