### ISSUE TITLE
Can you add more support for when_all, when_any and when_seq?

### ISSUE THREAD

**Issue by libaineu2004** [mhogomchungu/tasks#7]
Can you add more support for when_all, when_any and when_seq?
 Similar to this open source project:
https://github.com/Naios/continuable
https://naios.github.io/continuable/

**Comment by mhogomchungu** [comment]
"when_all" is already implemented and an example use cause is here: https://github.com/mhogomchungu/tasks/blob/9a395e027c537d9f9544a848682a97b3f065dd0b/example.cpp#L143-L179

**Comment by libaineu2004** [comment]
> "when_seq" is supposed to be doing what.
> 
> "when_all" is already implemented and an example use cause is here:
> 
> https://github.com/mhogomchungu/tasks/blob/9a395e027c537d9f9544a848682a97b3f065dd0b/example.cpp#L143-L179

good!
I hope you change the function name to when_all. What about "when_any"? Is there a plan to complete it?
thank you very much! Great work!

**Comment by mhogomchungu** [comment]
This[1] commit adds support for Task::when_all.

[1] https://github.com/mhogomchungu/tasks/commit/06595162e3e8fbe56ae0d5867aed94a9d1ffa56a

**Comment by libaineu2004** [comment]
> This[1] commit adds support for Task::when_all.
> 
> [1] [0659516](https://github.com/mhogomchungu/tasks/commit/06595162e3e8fbe56ae0d5867aed94a9d1ffa56a)

Well done

**Comment by mhogomchungu** [comment]
"when_any" API is now in with this[1] commit

"when_all" and "when_seq" were already implemented and i added these two[2] API to just alias existing API for those who are familiar with these new terms.

[1] https://github.com/mhogomchungu/tasks/commit/9ac8696e565a71cd2250f0fa83b70357183be40c

[2] https://github.com/mhogomchungu/tasks/blob/9ac8696e565a71cd2250f0fa83b70357183be40c/task.hpp#L204-L214

Closing it but feel free to comment if anything comes up.
