### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Fianax** [mhogomchungu/tasks#8]
I don't have much practice in installing libraries in qt. How is yours installed? It would be of great help to me for a project.

Thanks for reading me.

**Comment by mhogomchungu** [comment]
You dont install it, just copy the "task.hpp" file to your source code folder and do the normal ```#include "task.hpp"``` to include it to source file/header that want to use the library.

**Comment by Fianax** [comment]
Hahahah, sorry to be such a ... idiot.  Thank you for helping me thank you
