### ISSUE TITLE
Does it support windows?

### ISSUE THREAD

**Issue by anjisZhou** [mhogomchungu/tasks#9]
Does it support windows? Why can't I compile under windows?

**Comment by mhogomchungu** [comment]
Yes it does, what error are you getting?

**Comment by anjisZhou** [comment]
When I use qt5.15.2+msvc2019 to compile, it fails to compile and it prompts "Syntax error: identifier future", and it can be compiled using MinGW.

**Comment by wuwenjie5516** [comment]
me too.    find Same question

**Comment by mhogomchungu** [comment]
It did work in  MSVC2015[1], will install the latest MSVC this weekend and try to fix the issue.

[1] https://github.com/mhogomchungu/tasks/issues/5#issuecomment-411813221

**Comment by mhogomchungu** [comment]
Try now with a git version
